main: me.trumpetplayer2.CompNetworkProject.Main
name: CompNetworkProject
version: 0.0.1
description: Insert Description
author: Trumpetplayer2
api-version: 1.18

commands:
  networkpacket:
    description: Toggles network packet display
    usage: /networkpacket [true/false]
    aliases: [np, netpack, cnp]

permissions:
    compnetworkproject.*:
        description: Permissions. Not going to be used for this project
        default: false